#!/bin/bash

RESTART_DOCKER=""

function usage()
{
  echo ""
  echo "Usage: ${0} [-r|--restart-docker] [-h|--help] <kata|runc>"
  echo ""
  echo "Set the docker default runtime to either kata or runc."
  echo ""
  echo "-r|--restart-docker: Also restart docker when setting the default runtime"
  echo "-h|--help: Print this message"
  echo ""
}

ARGS=$(getopt -o rh -l restart-docker,help -- "${@}");
[ $? -ne 0 ] && usage && exit 1
set -e
eval set -- "$ARGS"
while true; do
  case "$1" in
    -r|--restart-docker) RESTART_DOCKER=1; shift;;
    -h|--help) usage; exit 0;;
    --)shift; break;;
  esac
done

RUNTIME="$1"
[ ! "$RUNTIME" = "kata" ] && [ ! "$RUNTIME" = "runc" ] && usage && exit 1

# kata is really kata-runtime
[ "$RUNTIME" = "kata" ] && RUNTIME="kata-runtime"

mkdir -p /etc/systemd/system/docker.service.d/
cat <<EOF > /etc/systemd/system/docker.service.d/50-runtime.conf
[Service]
Environment="DOCKER_DEFAULT_RUNTIME=--default-runtime $RUNTIME"
EOF

if [ -z "$RESTART_DOCKER" ]; then
  systemctl daemon-reload
  systemctl restart docker.service
else
  echo "Docker default runtime updated, reload systemd configuration and restart docker for changes to take effect"
fi
